include:
  - profile.dotfiles.zsh
  - profile.dotfiles.emacs
  - profile.dotfiles.tmux
  - profile.dotfiles.vim
  - profile.dotfiles.gnupg
  - profile.dotfiles.git
  - profile.dotfiles.pass
  - profile.dotfiles.weechat
  - profile.dotfiles.beets
  - profile.dotfiles.debuggers
  - profile.dotfiles.lxc
  - profile.dotfiles.vagrant
  - profile.dotfiles.debian
  - profile.dotfiles.nvim
  - profile.dotfiles.signing-party
  - profile.dotfiles.virtualenvwrapper
